### ISSUE TITLE
1.18.2のforge版がほしい

### ISSUE THREAD

**Issue by curtainch** [TORO-Server/MarumaSign#2]
以下同文

**Comment by malken21** [comment]
ForgeのModの開発経験はあまりないので私一人では厳しそうです。

**Comment by curtainch** [comment]
だったら、fabric版はむりですかね...?

**Comment by malken21** [comment]
1.18.2 Fabric版も難しそうです。
似たような機能のMod見つけてきました。このModで代替できるかもしれません。
https://www.curseforge.com/minecraft/mc-mods/signpic

**Comment by curtainch** [comment]
ありがとうございます

**Comment by curtainch** [comment]
closeしますね
